markdown: kramdown
layouts_dir: /theme/layout
logo: "theme/assets/images/ept_doc.png"
search_enabled: false
heading_anchors: true
extra:
  generator: false
includes_dir: /theme/includes/
sass:
  sass_dir: /theme/_sass/
keep_files:
  - /theme/asset/
env:
  - THEME_DIR: /theme
token: ${{ secrets.GH_PAT }}
product_name: "Github Pages"
product_logo: "icon.png"
product_version:
 - 17
