permissions:
  contents: read
  pages: write
  deployments: write
  id-token: write

name: Build & Deploy user guide

on:
  workflow_dispatch

# Workflow with two jobs: "Build" then "Deploy"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: Build page with Jekyll
        uses: actions/jekyll-build-pages@v1-beta
        with:
          source: ./docs
          destination: ./_site
          future: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive build output
        run: tar --dereference --hard-dereference --directory _site/ -cvf artifact.tar .

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: warn

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
